services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    networks:
      - default
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_DATABASE}
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    env_file: 
      - .env
    ports:
      - ${PORT}:8080
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - default
    volumes:
      - ./logs:/app/logs

networks:
  default:
    driver: bridge
